In [1]:
import pandas as pd 
import numpy as np

In [4]:
data = pd.DataFrame(
    {
        'text': ['people watch campusX', 'campusX watch campusX', 'people write comment', 'campusX write comment'], 'output': [1,1,0,0]
    }
)

In [5]:
data

,text,output
0,people watch campusX,1
1,campusX watch campusX,1
2,people write comment,0
3,campusX write comment,0


In [6]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [7]:
bow = cv.fit_transform(data['text'])

In [ ]:
print(cv.vocabulary_) # it showing index of vocabulary (alpha)

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}


In [13]:
print(bow[1].toarray())

[[2 0 0 1 0]]


In [14]:
print(bow[0].toarray())

[[1 0 1 1 0]]


In [15]:
cv.transform(['campusx watch and write comment of campusx']).toarray()

array([[2, 1, 0, 1, 1]])