In [2]:
import pandas as pd 
import numpy as np

In [3]:
data = pd.DataFrame(
    {
        'text': ['people watch campusX', 'campusX watch campusX', 'people write comment', 'campusX write comment'], 'output': [1,1,0,0]
    }
)

In [4]:
data

,text,output
0,people watch campusX,1
1,campusX watch campusX,1
2,people write comment,0
3,campusX write comment,0


In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer()

In [10]:
tfidf = tf.fit_transform(data['text']).toarray()
tfidf

array([[0.49681612, 0.        , 0.61366674, 0.61366674, 0.        ],
       [0.8508161 , 0.        , 0.        , 0.52546357, 0.        ],
       [0.        , 0.57735027, 0.57735027, 0.        , 0.57735027],
       [0.49681612, 0.61366674, 0.        , 0.        , 0.61366674]])

In [15]:
print(tf.idf_)

[1.22314355 1.51082562 1.51082562 1.51082562 1.51082562]


In [17]:
print(tf.get_feature_names_out())

['campusx' 'comment' 'people' 'watch' 'write']


In [14]:
print(tf.vocabulary_) # it showing index of vocabulary (alpha)

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}


In [ ]:
print(bow[1].toarray())

[[2 0 0 1 0]]


In [ ]:
print(bow[0].toarray())

[[1 0 1 1 0]]


In [ ]:
cv.transform(['campusx watch and write comment of campusx']).toarray()

array([[2, 1, 0, 1, 1]])